apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-oppfolgingsperiode
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-oppfolgingsperiode
      rules:
        - alert: toi-oppfolgingsperiode
          expr: sum(up{app="toi-oppfolgingsperiode", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/u5tEV"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-oppfolgingsperiode
          expr: sum(increase(logd_messages_total{log_app="toi-oppfolgingsperiode",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/u5tEV"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-oppfolgingsperiode
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-oppfolgingsperiode  ",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-oppfolgingsperiode  "}[5m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/u5tEV"
          labels:
            namespace: toi
            severity: warning
