apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-cv
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{{ kvPath }}}
        mountPath: /secret/serviceuser
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  azure:
    application:
      enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka_consumer_group_id}}
    - name: ARBEIDSPLASSEN_CV_KAFKA_GROUP
      value: {{arbeidsplassen_cv_kafka_group}}