apiVersion: 'nais.io/v1'
kind: 'Alert'
metadata:
  name: toi-arbeidsgiver-notifikasjon
  namespace: toi
  labels:
    team: toi
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: toi-arbeidsgiver-notifikasjon
      severity: danger
      expr: sum(up{app="toi-arbeidsgiver-notifikasjon", job="kubernetes-pods"}) == 0
      for: 1m
      description: Appen er nede (ingen Kubernetes-pods er oppe)
      action: "https://logs.adeo.no/app/r/s/Cr1VK"

    - alert: toi-arbeidsgiver-notifikasjon
      severity: danger
      expr: sum(increase(logd_messages_total{log_app="toi-arbeidsgiver-notifikasjon",log_level="Error"}[10m])) > 0
      for: 1s
      description: Appen har logget en error
      action: "https://logs.adeo.no/app/r/s/Cr1VK"

    - alert: toi-arbeidsgiver-notifikasjon
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-arbeidsgiver-notifikasjon",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-arbeidsgiver-notifikasjon"}[5m]))) > 20
      for: 5m
      description: Økning i warnings
      action: "https://logs.adeo.no/app/r/s/Cr1VK"
