apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-maa-behandle-tidligere-cv
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-maa-behandle-tidligere-cv
      rules:
        - alert: toi-maa-behandle-tidligere-cv
          expr: kube_deployment_status_replicas_available{deployment="toi-maa-behandle-tidligere-cv"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/fs550"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-maa-behandle-tidligere-cv
          expr: sum(increase(logd_messages_total{log_app="toi-maa-behandle-tidligere-cv",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/fs550"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-maa-behandle-tidligere-cv
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-maa-behandle-tidligere-cv  ",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-maa-behandle-tidligere-cv  "}[5m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/fs550"
          labels:
            namespace: toi
            severity: warning
