apiVersion: 'nais.io/v1'
kind: 'Alert'
metadata:
  name: toi-helseapp
  namespace: toi
  labels:
    team: toi
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: toi-helseapp
      severity: danger
      expr: sum(up{app="toi-helseapp", job="kubernetes-pods"}) == 0
      for: 1m
      description: Appen er nede (ingen Kubernetes-pods er oppe)
      action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"

    - alert: toi-helseapp
      expr: sum(increase(logd_messages_total{log_app="toi-helseapp",log_level="Error"}[10m])) > 0
      for: 1s
      description: Appen har logget en error
      action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"

    - alert: toi-helseapp
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-helseapp",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-helseapp"}[5m]))) > 10
      for: 5m
      description: Økning i warnings
      action: "https://logs.adeo.no/goto/2d965f50-0db3-11ed-9b1a-4723a5e7a9db"
