apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-helseapp
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1