apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-ontologitjeneste
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-ontologitjeneste
      rules:
        - alert: toi-ontologitjeneste
          expr: kube_deployment_status_replicas_available{deployment="toi-ontologitjeneste"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: sum(increase(logd_messages_total{log_app="toi-ontologitjeneste",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-ontologitjeneste  ",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-ontologitjeneste  "}[5m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/02nZX"
          labels:
            namespace: toi
            severity: warning
