apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-arbeidsplassen-cv-reader
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  azure:
    application:
      enabled: true
  env:
    - name: PAM_CV_TOPIC
      value: arbeid-pam-cv-endret-v6