apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: toi-kandidat-1
  namespace: toi
  labels:
    team: toi
spec:
  pool: nav-dev
  config: # optional; all fields are optional too
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1 # -1 means unlimited
    retentionHours: -1 # -1 means unlimited
  acl:
    - team: toi
      application: toi-kandidatfeed
      access: readwrite # read, write, readwrite
    - team: arbeidsgiver-inkludering
      application: arbeidsgiver-inkludering-kafkamanager
      access: readwrite # read, write, readwrite
    - team: arbeidsgiver
      application: rekrutteringsbistand-kandidat-indekser
      access: read # read, write, readwrite