apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-sammenstill-kandidat
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: toi-sammenstill-kandidat-mongodb
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka_consumer_group_id}}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: MONGODB_URL
      value: mongodb://toi-sammenstill-kandidat-mongodb-0.toi-sammenstill-kandidat-mongodb:27017,toi-sammenstill-kandidat-mongodb-1.toi-sammenstill-kandidat-mongodb:27017,toi-sammenstill-kandidat-mongodb-2.toi-sammenstill-kandidat-mongodb:27017/deploy_log?replicaSet=MainRepSet
    - name: MONGODB_SERVER_URL
      value: mongodb+srv://server.toi-sammenstill-kandidat-mongodb/