name: Deploy toi-sammenstill-kandidat-mongodb to dev

on:
  push:
    branches:
      - main
    paths:
      - apps/toi-sammenstill-kandidat/mongo/mongo-dev.yml
      - apps/toi-sammenstill-kandidat/mongo/mongo-network-policy.yml
      - apps/toi-sammenstill-kandidat/mongo/mongo-service.yml

jobs:
  deploy-mongo-to-dev:
    name: Deploy mongo to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/toi-sammenstill-kandidat/mongo/mongo-dev.yml
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/toi-sammenstill-kandidat/mongo/mongo-network-policy.yml
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/toi-sammenstill-kandidat/mongo/mongo-service.yml