name: Deploy kandidat-topic to prod

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-topic-kandidat-to-prod.yaml
      - apps/toi-kandidatfeed/topic-kandidat-prod.yml

jobs:
  deploy-kandidat-topic-to-prod:
    name: Deploy kandidat-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/toi-kandidatfeed/topic-kandidat-prod.yml