name: Deploy kandidat topic to dev

on:
  push:
    branches:
      - main
    paths:
      - apps/toi-kandidatfeed/topic-kandidat-dev.yml

jobs:
  deplo-kandidat-topic-to-dev:
    name: Deploy kandidat topic to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: topic-kandidat-dev.yml