name: Snyk monitor
on:
  push:
    branches:
      - main
jobs:
  snyk-monitor:
    name: Monitor dependencies with Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk monitor --org=toi --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}